name: codesandbox
on: pull_request
jobs:
  annotate_pull_request:
    runs-on: ubuntu-latest
    name: perform annotation
    steps:
      - name: annotation action step
        id: annotation
        uses: kherin/pr-comment-action@v1.0.1
        with:
          annotation-url: "https://githubbox.com/"
          token: ${{ secrets.GITHUB_TOKEN }}
